import os

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_PATH = os.path.join(_PROJECT_ROOT, "data", "jelek")
MODEL_PATH = os.path.join(_PROJECT_ROOT, "your_model.pth")
EVALUATION_REPORT_PATH = os.path.join(_PROJECT_ROOT, "ertekelesi_jelentes.txt")
EVALUATION_CONFUSION_PNG_PATH = os.path.join(_PROJECT_ROOT, "ertekelesi_confusion_matrix.png")

POSE_DIMS = 33 * 4
FACE_DIMS = 468 * 3
HAND_DIMS = 21 * 3
INPUT_SIZE = POSE_DIMS + FACE_DIMS + HAND_DIMS + HAND_DIMS

POSE_FEATURE_SCALE = 1.0
FACE_FEATURE_SCALE = 0.35
HAND_FEATURE_SCALE = 3.5
HIDDEN_SIZE = 64
NO_SEQUENCES = 30
SEQUENCE_LENGTH = 31
PAUSE_BETWEEN_SEQUENCES_SEC = 1.0
BATCH_SIZE = 32
EPOCHS = 30
GRAD_CLIP_MAX_NORM = 1.0

MIN_RECOGNITION_FRAMES = 10
CONFIDENCE_THRESHOLD = 0.5
PREDICTION_SMOOTHING_WINDOW = 5
PREDICTION_HOLD_FRAMES = 5
RECOGNITION_INPUT_WIDTH = 256
TOP_N_CONFUSED_PAIRS = 15
TOP_N_BEST_CLASSES = 5
TOP_N_WORST_CLASSES = 5
